### ISSUE TITLE
pygreentea.netgen has no create_nets function

### ISSUE THREAD

**Issue by stevendbrown** [naibaf7/caffe_neural_models#4]
after updating `pygt_01/script.py` to load `pygreentea` instead of `PyGreentea` i get an error that a function isn't found (create_nets). looking through the current version of PyGreentea, i can't seem to find the `create_nets` function called by this module. apologies if i'm missing something obvious; maybe PyGreentea is on a very old version compared to what this repo uses?

**Comment by naibaf7** [comment]
yes the code changed significantly, it now has a more flexible Metalayer structure. New usage examples can be found in this repository.

**Comment by stevendbrown** [comment]
do you mean a newer version of PyGreentea is available as part of caffe_neural_models?

**Comment by naibaf7** [comment]
Ah no, with reference to the newest version here:
https://github.com/naibaf7/PyGreentea
The valid examples are now here:
https://github.com/naibaf7/PyGreentea/tree/master/examples

This (https://github.com/naibaf7/caffe_neural_models/) repository is considered obsoloete and for use with older PyGreentea versions and the C++ caffe_neural_tool, both of which belong to my original thesis.

Feel free to ask for different kind of examples (w.r.t data input, network shape or loss functions or dimensionality), so I can provide them.

**Comment by stevendbrown** [comment]
ah, i see. i'll add follow-up questions to that repository when i've worked through the examples there. thank you for making your work available!
